// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALY4zbI6VCQVPXGSzze2EvAIy4NXoCjsw',
    appId: '1:439736446453:web:d8d88187583311f43384bc',
    messagingSenderId: '439736446453',
    projectId: 'al-mumtazun-realtime',
    authDomain: 'al-mumtazun-realtime.firebaseapp.com',
    storageBucket: 'al-mumtazun-realtime.firebasestorage.app',
    measurementId: 'G-MNLV6452QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdM2df-lfTX5ge7OWbduy1ZJc-N69O6Mw',
    appId: '1:439736446453:android:af18a1f0e2e65d893384bc',
    messagingSenderId: '439736446453',
    projectId: 'al-mumtazun-realtime',
    storageBucket: 'al-mumtazun-realtime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxaIVDrctdZ3G2qrZxNngnGSRNvU9zsfI',
    appId: '1:439736446453:ios:df0777d62f558d1f3384bc',
    messagingSenderId: '439736446453',
    projectId: 'al-mumtazun-realtime',
    storageBucket: 'al-mumtazun-realtime.firebasestorage.app',
    iosBundleId: 'com.example.engineeringOpsDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxaIVDrctdZ3G2qrZxNngnGSRNvU9zsfI',
    appId: '1:439736446453:ios:df0777d62f558d1f3384bc',
    messagingSenderId: '439736446453',
    projectId: 'al-mumtazun-realtime',
    storageBucket: 'al-mumtazun-realtime.firebasestorage.app',
    iosBundleId: 'com.example.engineeringOpsDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALY4zbI6VCQVPXGSzze2EvAIy4NXoCjsw',
    appId: '1:439736446453:web:3630e4444fd9620b3384bc',
    messagingSenderId: '439736446453',
    projectId: 'al-mumtazun-realtime',
    authDomain: 'al-mumtazun-realtime.firebaseapp.com',
    storageBucket: 'al-mumtazun-realtime.firebasestorage.app',
    measurementId: 'G-K2RPFS1KLL',
  );
}
