// lib/features/income/income_screen.dart

import 'package:flutter/material.dart';
import '../../theme/app_colors.dart';
import '../../localization/l10n.dart';

class IncomeScreen extends StatelessWidget {
  const IncomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final bool isWide = MediaQuery.of(context).size.width >= 1024;
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: isWide ? _buildWideLayout(context) : _buildNarrowLayout(context),
    );
  }

  Widget _buildWideLayout(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: const [
        Expanded(flex: 4, child: _LeftColumn()),
        SizedBox(width: 16),
        Expanded(flex: 8, child: _EntryForm()),
      ],
    );
  }

  Widget _buildNarrowLayout(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: const [
        _LeftColumn(),
        SizedBox(height: 16),
        _EntryForm(),
      ],
    );
  }
}

// ------------------------------------------------------------------
// Left column containing Overview and Visualization cards
// ------------------------------------------------------------------
class _LeftColumn extends StatelessWidget {
  const _LeftColumn({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: const [
        _OverviewCard(),
        SizedBox(height: 16),
        _VisualizationCard(),
      ],
    );
  }
}

class _OverviewCard extends StatelessWidget {
  const _OverviewCard({super.key});

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              l10n.income, // "Income"
              style: Theme.of(context).textTheme.headlineSmall!.copyWith(color: AppColors.primary),
            ),
            const SizedBox(height: 8),
            const Text(
              "Ensure all daily earnings generated by engineering staff are logged accurately to maintain precise financial reporting and performance tracking.",
              style: TextStyle(color: AppColors.onSurfaceVariant),
            ),
            const SizedBox(height: 16),
            _InfoRow(
              icon: Icons.trending_up,
              label: "Daily Target",
              value: r"$12,500.00",
            ),
            const SizedBox(height: 8),
            _InfoRow(
              icon: Icons.verified_user,
              label: "Compliance",
              value: "High",
            ),
          ],
        ),
      ),
    );
  }
}

class _InfoRow extends StatelessWidget {
  final IconData icon;
  final String label;
  final String value;
  const _InfoRow({required this.icon, required this.label, required this.value, super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(
        color: AppColors.surfaceContainerLow,
        borderRadius: BorderRadius.circular(8),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Row(
            children: [
              Icon(icon, color: AppColors.secondary),
              const SizedBox(width: 8),
              Text(label.toUpperCase(), style: const TextStyle(fontWeight: FontWeight.w600, letterSpacing: 0.5)),
            ],
          ),
          Text(value, style: Theme.of(context).textTheme.bodyLarge!.copyWith(color: AppColors.primary)),
        ],
      ),
    );
  }
}

class _VisualizationCard extends StatelessWidget {
  const _VisualizationCard({super.key});

  @override
  Widget build(BuildContext context) {
    return Card(
      clipBehavior: Clip.antiAlias,
      child: AspectRatio(
        aspectRatio: 16 / 9,
        child: Stack(
          children: [
            // Image from the original HTML (network image).
            Positioned.fill(
              child: Image.network(
                'https://lh3.googleusercontent.com/aida-public/AB6AXuBPpRE0sHhPjdf0QOpFL0JNNSeqh9-inii213YVQQTO_xku4HMhB9fRo9JBaCYeuHJMSBgFY5pkj3yRN_9X0M_R59jcmFJO9kTBE4rOj20GpLD-9PRTvBDM2bi-5v4YoeNvJWXc97kzSLWJzAfrB-chlj4OKq-OBDlk0nmfpUrp5X0DldJEn8bfmuDQElko1de7xO1mk1PA9mchdOqGRru-ongByXNuDGNNm6gpMlLKsYc0G1Wb5mk2BpoAVPylARVYqtV8nAXkBL7e',
                fit: BoxFit.cover,
                color: AppColors.primary.withOpacity(0.4),
                colorBlendMode: BlendMode.darken,
              ),
            ),
            Positioned(
              bottom: 0,
              left: 0,
              right: 0,
              child: Container(
                color: AppColors.primary.withOpacity(0.4),
                padding: const EdgeInsets.all(8),
                child: const Text(
                  'System Status: Active',
                  style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                  textAlign: TextAlign.center,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ------------------------------------------------------------------
// Entry form (right column)
// ------------------------------------------------------------------
class _EntryForm extends StatefulWidget {
  const _EntryForm({super.key});

  @override
  State<_EntryForm> createState() => _EntryFormState();
}

class _EntryFormState extends State<_EntryForm> {
  final _formKey = GlobalKey<FormState>();
  DateTime? _selectedDate;
  String? _selectedEngineer;
  double? _amount;
  String? _notes;

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: const [
                  Icon(Icons.payments, color: AppColors.secondary),
                  SizedBox(width: 8),
                ],
              ),
              const SizedBox(height: 8),
              Text(l10n.income, style: Theme.of(context).textTheme.headlineMedium),
              const SizedBox(height: 16),
              // Date field
              _FormFieldLabel(label: 'Date'),
              const SizedBox(height: 4),
              GestureDetector(
                onTap: _pickDate,
                child: InputDecorator(
                  decoration: InputDecoration(
                    filled: true,
                    fillColor: Colors.white,
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: const BorderSide(color: AppColors.outlineVariant)),
                    suffixIcon: const Icon(Icons.calendar_today, color: AppColors.onSurfaceVariant),
                  ),
                  child: Text(_selectedDate != null ? _formatDate(_selectedDate!) : 'Select date'),
                ),
              ),
              const SizedBox(height: 16),
              // Engineer dropdown
              _FormFieldLabel(label: 'Engineer'),
              const SizedBox(height: 4),
              DropdownButtonFormField<String>(
                decoration: InputDecoration(
                  filled: true,
                  fillColor: Colors.white,
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: const BorderSide(color: AppColors.outlineVariant)),
                  suffixIcon: const Icon(Icons.expand_more, color: AppColors.onSurfaceVariant),
                ),
                items: const [
                  DropdownMenuItem(value: '', child: Text('Select an Engineer')),
                  DropdownMenuItem(value: '1', child: Text('Eng. Sarah Jenkins (Senior Lead)')),
                  DropdownMenuItem(value: '2', child: Text('Eng. Michael Chen (Hardware)')),
                  DropdownMenuItem(value: '3', child: Text('Eng. Robert Smith (Software)')),
                  DropdownMenuItem(value: '4', child: Text('Eng. Elena Rodriguez (QA)')),
                ],
                onChanged: (val) => setState(() => _selectedEngineer = val),
                validator: (v) => (v == null || v.isEmpty) ? 'Please select an engineer' : null,
              ),
              const SizedBox(height: 16),
              // Amount field
              _FormFieldLabel(label: 'Amount (USD)'),
              const SizedBox(height: 4),
              TextFormField(
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                decoration: InputDecoration(
                  prefixText: '\$',
                  filled: true,
                  fillColor: Colors.white,
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: const BorderSide(color: AppColors.outlineVariant)),
                ),
                validator: (v) => (v == null || v.isEmpty) ? 'Enter amount' : null,
                onSaved: (v) => _amount = double.tryParse(v ?? ''),
              ),
              const SizedBox(height: 16),
              // Notes field
              _FormFieldLabel(label: 'Notes'),
              const SizedBox(height: 4),
              TextFormField(
                maxLines: 4,
                decoration: InputDecoration(
                  filled: true,
                  fillColor: Colors.white,
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: const BorderSide(color: AppColors.outlineVariant)),
                ),
                onSaved: (v) => _notes = v,
              ),
              const SizedBox(height: 24),
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: () => _formKey.currentState?.reset(),
                    child: const Text('Cancel'),
                  ),
                  const SizedBox(width: 12),
                  ElevatedButton.icon(
                    onPressed: _submit,
                    icon: const Icon(Icons.send),
                    label: const Text('Submit Entry'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.secondary,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _pickDate() async {
    final now = DateTime.now();
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: now,
      firstDate: DateTime(now.year - 5),
      lastDate: DateTime(now.year + 5),
    );
    if (picked != null) {
      setState(() => _selectedDate = picked);
    }
  }

  String _formatDate(DateTime d) => '${d.year}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';

  void _submit() {
    if (_formKey.currentState?.validate() ?? false) {
      _formKey.currentState?.save();
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Entry submitted (demo)')),
      );
    }
  }
}

class _FormFieldLabel extends StatelessWidget {
  final String label;
  const _FormFieldLabel({required this.label, super.key});

  @override
  Widget build(BuildContext context) {
    return Text(
      label,
      style: const TextStyle(fontWeight: FontWeight.w600, letterSpacing: 0.5),
    );
  }
}
